# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='main',
  syntax='proto3',
  serialized_options=b'Z?github.com/maxime-lair/grpc-goclient-pythonserver/goclient/main',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\x12\x04main\"\x1a\n\nSocketTree\x12\x0c\n\x04name\x18\x01 \x01(\t\"P\n\x0cSocketFamily\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12#\n\tclient_id\x18\x03 \x01(\x0b\x32\x10.main.SocketTree\"N\n\nSocketType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12#\n\tclient_id\x18\x03 \x01(\x0b\x32\x10.main.SocketTree\"~\n\x13SocketTypeAndFamily\x12\"\n\x06\x66\x61mily\x18\x01 \x01(\x0b\x32\x12.main.SocketFamily\x12\x1e\n\x04type\x18\x02 \x01(\x0b\x32\x10.main.SocketType\x12#\n\tclient_id\x18\x03 \x01(\x0b\x32\x10.main.SocketTree\"R\n\x0eSocketProtocol\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12#\n\tclient_id\x18\x03 \x01(\x0b\x32\x10.main.SocketTree2\xdb\x01\n\x0bSocketGuide\x12?\n\x13GetSocketFamilyList\x12\x10.main.SocketTree\x1a\x12.main.SocketFamily\"\x00\x30\x01\x12=\n\x11GetSocketTypeList\x12\x12.main.SocketFamily\x1a\x10.main.SocketType\"\x00\x30\x01\x12L\n\x15GetSocketProtocolList\x12\x19.main.SocketTypeAndFamily\x1a\x14.main.SocketProtocol\"\x00\x30\x01\x42\x41Z?github.com/maxime-lair/grpc-goclient-pythonserver/goclient/mainb\x06proto3'
)




_SOCKETTREE = _descriptor.Descriptor(
  name='SocketTree',
  full_name='main.SocketTree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='main.SocketTree.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=48,
)


_SOCKETFAMILY = _descriptor.Descriptor(
  name='SocketFamily',
  full_name='main.SocketFamily',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='main.SocketFamily.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='main.SocketFamily.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='main.SocketFamily.client_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=130,
)


_SOCKETTYPE = _descriptor.Descriptor(
  name='SocketType',
  full_name='main.SocketType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='main.SocketType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='main.SocketType.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='main.SocketType.client_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=210,
)


_SOCKETTYPEANDFAMILY = _descriptor.Descriptor(
  name='SocketTypeAndFamily',
  full_name='main.SocketTypeAndFamily',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='family', full_name='main.SocketTypeAndFamily.family', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='main.SocketTypeAndFamily.type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='main.SocketTypeAndFamily.client_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=338,
)


_SOCKETPROTOCOL = _descriptor.Descriptor(
  name='SocketProtocol',
  full_name='main.SocketProtocol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='main.SocketProtocol.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='main.SocketProtocol.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='main.SocketProtocol.client_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=422,
)

_SOCKETFAMILY.fields_by_name['client_id'].message_type = _SOCKETTREE
_SOCKETTYPE.fields_by_name['client_id'].message_type = _SOCKETTREE
_SOCKETTYPEANDFAMILY.fields_by_name['family'].message_type = _SOCKETFAMILY
_SOCKETTYPEANDFAMILY.fields_by_name['type'].message_type = _SOCKETTYPE
_SOCKETTYPEANDFAMILY.fields_by_name['client_id'].message_type = _SOCKETTREE
_SOCKETPROTOCOL.fields_by_name['client_id'].message_type = _SOCKETTREE
DESCRIPTOR.message_types_by_name['SocketTree'] = _SOCKETTREE
DESCRIPTOR.message_types_by_name['SocketFamily'] = _SOCKETFAMILY
DESCRIPTOR.message_types_by_name['SocketType'] = _SOCKETTYPE
DESCRIPTOR.message_types_by_name['SocketTypeAndFamily'] = _SOCKETTYPEANDFAMILY
DESCRIPTOR.message_types_by_name['SocketProtocol'] = _SOCKETPROTOCOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocketTree = _reflection.GeneratedProtocolMessageType('SocketTree', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETTREE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:main.SocketTree)
  })
_sym_db.RegisterMessage(SocketTree)

SocketFamily = _reflection.GeneratedProtocolMessageType('SocketFamily', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETFAMILY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:main.SocketFamily)
  })
_sym_db.RegisterMessage(SocketFamily)

SocketType = _reflection.GeneratedProtocolMessageType('SocketType', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETTYPE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:main.SocketType)
  })
_sym_db.RegisterMessage(SocketType)

SocketTypeAndFamily = _reflection.GeneratedProtocolMessageType('SocketTypeAndFamily', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETTYPEANDFAMILY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:main.SocketTypeAndFamily)
  })
_sym_db.RegisterMessage(SocketTypeAndFamily)

SocketProtocol = _reflection.GeneratedProtocolMessageType('SocketProtocol', (_message.Message,), {
  'DESCRIPTOR' : _SOCKETPROTOCOL,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:main.SocketProtocol)
  })
_sym_db.RegisterMessage(SocketProtocol)


DESCRIPTOR._options = None

_SOCKETGUIDE = _descriptor.ServiceDescriptor(
  name='SocketGuide',
  full_name='main.SocketGuide',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=425,
  serialized_end=644,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSocketFamilyList',
    full_name='main.SocketGuide.GetSocketFamilyList',
    index=0,
    containing_service=None,
    input_type=_SOCKETTREE,
    output_type=_SOCKETFAMILY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSocketTypeList',
    full_name='main.SocketGuide.GetSocketTypeList',
    index=1,
    containing_service=None,
    input_type=_SOCKETFAMILY,
    output_type=_SOCKETTYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSocketProtocolList',
    full_name='main.SocketGuide.GetSocketProtocolList',
    index=2,
    containing_service=None,
    input_type=_SOCKETTYPEANDFAMILY,
    output_type=_SOCKETPROTOCOL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOCKETGUIDE)

DESCRIPTOR.services_by_name['SocketGuide'] = _SOCKETGUIDE

# @@protoc_insertion_point(module_scope)
