# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class SocketGuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSocketFamilyList = channel.unary_stream(
                '/pb_server.SocketGuide/GetSocketFamilyList',
                request_serializer=server__pb2.SocketTree.SerializeToString,
                response_deserializer=server__pb2.SocketFamily.FromString,
                )
        self.GetSocketTypeList = channel.unary_stream(
                '/pb_server.SocketGuide/GetSocketTypeList',
                request_serializer=server__pb2.SocketFamily.SerializeToString,
                response_deserializer=server__pb2.SocketType.FromString,
                )
        self.GetSocketProtocolList = channel.unary_stream(
                '/pb_server.SocketGuide/GetSocketProtocolList',
                request_serializer=server__pb2.SocketTypeAndFamily.SerializeToString,
                response_deserializer=server__pb2.SocketProtocol.FromString,
                )


class SocketGuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSocketFamilyList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSocketTypeList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSocketProtocolList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocketGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSocketFamilyList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSocketFamilyList,
                    request_deserializer=server__pb2.SocketTree.FromString,
                    response_serializer=server__pb2.SocketFamily.SerializeToString,
            ),
            'GetSocketTypeList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSocketTypeList,
                    request_deserializer=server__pb2.SocketFamily.FromString,
                    response_serializer=server__pb2.SocketType.SerializeToString,
            ),
            'GetSocketProtocolList': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSocketProtocolList,
                    request_deserializer=server__pb2.SocketTypeAndFamily.FromString,
                    response_serializer=server__pb2.SocketProtocol.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb_server.SocketGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SocketGuide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSocketFamilyList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pb_server.SocketGuide/GetSocketFamilyList',
            server__pb2.SocketTree.SerializeToString,
            server__pb2.SocketFamily.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSocketTypeList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pb_server.SocketGuide/GetSocketTypeList',
            server__pb2.SocketFamily.SerializeToString,
            server__pb2.SocketType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSocketProtocolList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pb_server.SocketGuide/GetSocketProtocolList',
            server__pb2.SocketTypeAndFamily.SerializeToString,
            server__pb2.SocketProtocol.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
